"""add company id to application table

Revision ID: ab91ef855352
Revises: 1b425287e9a4
Create Date: 2026-05-12 18:11:48.296195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab91ef855352'
down_revision: Union[str, None] = '1b425287e9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_applications_company_id'), 'applications', ['company_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'company_profiles', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_company_id'), table_name='applications')
    op.drop_column('applications', 'company_id')
    # ### end Alembic commands ###
